# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: 'Upload artifact'
        required: true
        default: 'true'    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add PostgreSQL provider
      run: dotnet add package Npgsql
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output dotnet_app
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip Directory
      run: |
        zip -r dotnet_app.zip dotnet_app
    - name: Prepare for Upload
      run: |
        mkdir /tmp/upload
        mv dotnet_app.zip /tmp/upload/
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::612548706164:role/github-actions-s3-upload
        aws-region: eu-north-1    
    - if: github.event.inputs.upload_artifact == 'true'
      name: Upload to S3
      id: S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: /tmp/upload
        
